### PR TITLE
Added RadixSort.py

### PR DESCRIPTION
**Pull request by StephenTrainor**
Here is my attempt at adding radix sort to the project. I am open to suggestions, edits, criticism, etc.
If you wouldn't mind adding the 'hacktoberfest-accepted' label onto this PR if you accept.

### CODE REVIEW

**Comment by jordanhilado** [comment]
Looks great, but are you able to implement your algorithm into sortingAlgs.py in order for the application to work properly? If that can be done I would be more than willing to merge it! @StephenTrainor

**Comment by StephenTrainor** [comment]
Okay, I will try to add that.

**Comment by StephenTrainor** [comment]
With the way I made my functions, I don't take in these 'timeTick' parameters. But when I added them in and tried to implement them with the Tkinter window thing, I got a few different errors. I got importing errors, and I tried importing in multiple places. Then, when running the window and clicking on start with radix sort selected, the window would not respond and I would have to close it. Finally, I tried removing everything and just passing in the data or array, which worked fine. The one thing being the sorting is so fast you do not see the sorting process. Any suggestions about what to do?

**Comment by StephenTrainor** [comment]
Also, I manually tried to add a time.sleep(0.1) and time.sleep(1) everywhere in my functions and the window would just say 'not responding'.

**Comment by jordanhilado** [comment]
From my understanding, I initially had some problems too when viewing the algorithms in action, but adjusting the timer slider should slow things down before running an algorithm. If that doens't work then it might be your operating system. The `root.update()` is responsible for displaying the algorithmic process step-by-step. If you are using Windows, this might need to be changed for you to view the algorithms properly, but if you are on MacOS, it should be running fine. Other than that you might want to look at the other merged algorithms done by others and see how they were able to implement the `timeTick` parameters.

**Comment by StephenTrainor** [comment]
I tried to add in the timeTick parameters, which froze the window again. However, I am on windows so that might be the problem. I will double check and try a few more things.

**Comment by StephenTrainor** [comment]
I added some changes so the window doesn't crash when I press start. However, once the sorting is finished, the green bars kinda keep iterating over the numbers even though they are sorted. Is there a way I can just make all of the bars green at the end? I saw this line `drawData(data, ['green' for x in range(len(data))])` in sortingAlgs.py but I don't think it is executing.

**Comment by jordanhilado** [comment]
I believe that's the correct line for setting all the bars green once sorted, but to be honest I don't have a preference on the colors, I would just like for it to display itself sorting through itself by its desired sorting algorithm, and have it preferably all green at the end. If this isn't possible, but everything else works completely fine without any issues I am more than willing to merge.

**Comment by StephenTrainor** [comment]
Good news! I found the infinite loop and put an if statement to fix it. The bars at the end are all green just as expected!

**Comment by jordanhilado** [comment]
Looks great! Just has one conflict to be resolved then I'll be merging!

**Comment by StephenTrainor** [comment]
I think that resolved the conflict. It was just one line.

**Comment by StephenTrainor** [comment]
If you don't mind and have some extra time, would you mind putting the 'hacktoberfest-accepted' label on this PR?

**Pull request merged**
