### PR TITLE
Create heapSort.py

### PR DESCRIPTION
**Pull request by ravidyarev**
Issue#1 to add another sorting algorithm

### CODE REVIEW

**Comment by jordanhilado** [comment]
Looks great, but the file sortingAlgs.py needs to be changed whenever a new algorithm is implemented. If possible are you able to do this? @ravidyarev

**Comment by ravidyarev** [comment]
> Looks great, but the file sortingAlgs.py needs to be changed whenever a new algorithm is implemented. If possible are you able to do this? @ravidyarev

Let me try to attempt that, thank you @jordanhilado

**Comment by ravidyarev** [comment]
@jordanhilado implementing the time tick is getting very difficult for me. I'll revert my pull request, Thank you for letting me try.

**Comment by jordanhilado** [comment]
I definitely appreciate the time and effort, thanks! @ravidyarev

**Pull request closed without merging**
